# Generated by Django 5.1.7 on 2026-03-31 22:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import syncer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Silicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, numbers, hyphens, and underscores.', regex='^[a-z0-9][a-z0-9_-]*$')])),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('api_key', models.CharField(default='', editable=False, max_length=64, unique=True)),
                ('api_key_last_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silicons', to='accounts.carbon')),
            ],
            options={
                'db_table': 'silicons',
            },
        ),
        migrations.CreateModel(
            name='ConnectorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_by_label', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('silicon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_codes', to='syncer.silicon')),
            ],
            options={
                'db_table': 'connector_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_label', models.CharField(max_length=255)),
                ('folder_fingerprint', models.CharField(max_length=128)),
                ('source_token', models.CharField(max_length=64, unique=True)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('last_push_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connector_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syncer.connectorcode')),
                ('silicon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_bindings', to='syncer.silicon')),
            ],
            options={
                'db_table': 'source_bindings',
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_hash', models.CharField(max_length=64)),
                ('archive', models.FileField(upload_to=syncer.models.snapshot_upload_path)),
                ('archive_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('silicon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='syncer.silicon')),
                ('binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='syncer.sourcebinding')),
            ],
            options={
                'db_table': 'snapshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
