# Generated by Django 5.1.7 on 2026-04-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='silicon',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='silicon',
            name='reported_status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
