# Generated by Django 5.1.7 on 2026-03-31 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syncer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiliconThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads_as_a', to='syncer.silicon')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads_as_b', to='syncer.silicon')),
            ],
            options={
                'db_table': 'silicon_threads',
            },
        ),
        migrations.CreateModel(
            name='SiliconMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio')], default='text', max_length=16)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='message_attachments/')),
                ('attachment_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='syncer.silicon')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.siliconmessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='syncer.silicon')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.siliconthread')),
            ],
            options={
                'db_table': 'silicon_messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='siliconthread',
            constraint=models.UniqueConstraint(fields=('a', 'b'), name='unique_silicon_thread_pair'),
        ),
    ]
