# Generated by Django 5.1.7 on 2026-04-02 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('syncer', '0002_add_heartbeat_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebugLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('silicon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debug_logs', to='syncer.silicon')),
            ],
            options={
                'db_table': 'debug_logs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RemoteCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('start', 'Start'), ('stop', 'Stop'), ('restart', 'Restart')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ack', 'Acknowledged'), ('done', 'Done'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.carbon')),
                ('silicon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='syncer.silicon')),
            ],
            options={
                'db_table': 'remote_commands',
                'ordering': ['-created_at'],
            },
        ),
    ]
